### ISSUE TITLE
Make it works with Python 3.5

### ISSUE THREAD

**Issue by M5oul** [tracycool/easycommandline#1]
Hi @tracycool, this lib looks awesome.
I could make it works with python 2.7 but not with python 3.5.

There is some issue importing:

``` bash
python3 cmd.py 
Traceback (most recent call last):
  File "cmd.py", line 1, in <module>
    from easycommandline import program
  File "easycommandline/examples/easycommandline/__init__.py", line 1, in <module>
    from easycommandline import program
ImportError: cannot import name 'program'
```

I tried to modify `__init__.py` and `easycommandline.py` imports headers.
I don't really understand why `eval()` function is used for at the end of `easycommandline.py` file.

Do you think it's easy to port this code to Python 3?
Will you do it?
Do there is other python3 lib like this one?
I couldn't found other great ones like this one.
I found that strange that no one ever report that issue.

Thanks.

**Comment by M5oul** [comment]
Anyway, I found an other great lib to manage commands and options which handle Python 3.5:
- [commandlines](https://pypi.python.org/pypi/commandlines).

I let open the ticket in case someone have same issue.

**Comment by truongdothienhoang** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.
